### ISSUE TITLE
Failed to install `gzip` module

### ISSUE THREAD

**Issue by Dev-Dipesh** [awslabs/aws-config-to-elasticsearch#1]
**PIP Version**

```
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Input**

```
$ pip install -r ./requirements.txt
```

**Output**

``` js
Could not find any downloads that satisfy the requirement gzip (from -r ./requirements.txt (line 4))
Cleaning up...
No distributions at all found for gzip (from -r ./requirements.txt (line 4))
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

**Detailed Logs**

``` js
Downloading/unpacking gzip (from -r ./requirements.txt (line 4))
  Getting page https://pypi.python.org/simple/gzip/
  Could not fetch URL https://pypi.python.org/simple/gzip/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/gzip/ when looking for download links for gzip (from -r ./requirements.txt (line 4))
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for gzip (from -r ./requirements.txt (line 4)):
  * https://pypi.python.org/simple/gzip/
  Getting page https://pypi.python.org/simple/gzip/
  Could not fetch URL https://pypi.python.org/simple/gzip/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/gzip/ when looking for download links for gzip (from -r ./requirements.txt (line 4))
  Could not find any downloads that satisfy the requirement gzip (from -r ./requirements.txt (line 4))
Cleaning up...
  Removing temporary dir /tmp/pip_build_ubuntu...
No distributions at all found for gzip (from -r ./requirements.txt (line 4))
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for gzip (from -r ./requirements.txt (line 4))
```

**Tried updating PIP**

Input

```
$ sudo pip install --upgrade pip
```

O/P

``` js
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

**Comment by vbudilov** [comment]
Hi @Dev-Dipesh , please upgrade pip and try again. In your case, you might want to remove pip completely and install it anew. The error you're seeing is most likely due to the extremely old version of pip. 

Thanks,
Vladimir

**Comment by vbudilov** [comment]
Hi @Dev-Dipesh, I'm closing this issue since it doesn't look like an issue with the code itself. Please reopen it if you feel it was closed prematurely.

**Comment by Dev-Dipesh** [comment]
Thanks, @vbudilov, the pip was pre-installed with the default AWS AMI in the marketplace. As you said, I figured the error is because of extremely old version, however, I can't even update it.

Installing from scratch might be the only option. You can add some description about this or the ami to use in your readme file.

Best

**Comment by yupyvovarov** [comment]
Hi @vbudilov 
I have exactly the same issue:
```
$ pip -V
pip 19.0.1 from ~/.pyenv/versions/aws_config_to_es/lib/python2.7/site-packages/pip (python 2.7)
$ pip install gzip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting gzip
  Could not find a version that satisfies the requirement gzip (from versions: )
No matching distribution found for gzip
```

**Comment by Bkowiec** [comment]
`ERROR: Could not find a version that satisfies the requirement gzip (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for gzip (from -r requirements.txt (line 3))`

**Comment by Bkowiec** [comment]
@vbudilov @yupvr 
`ERROR: Could not find a version that satisfies the requirement 
gzip (from -r requirements.txt (line 3)) (from versions: none)`

`ERROR: No matching distribution found for gzip (from -r requirements.txt (line 3))`

**Comment by chinmaya-dehury** [comment]
Try to remove it from the `requirement.txt` file. 
I was having the same issue while compressing the data in Azure function. I was expecting needs to be included in the requirement file. But I noticed that gzip is inbuilt, so you dont have to install explicitly.
